#!/usr/bin/env bash
# End-to-end verification. Runs every script's self-test, then drives the full
# pipeline on synthetic data, then proves the PII scanner is clean.
# Exits non-zero on the first failure so CI fails loudly.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

pass() { printf '  \033[32mok\033[0m   %s\n' "$1"; }
fail() { printf '  \033[31mFAIL\033[0m %s\n' "$1"; exit 1; }

echo "== unit self-tests =="
python3 scripts/normalize_raw_dna.py --self-test >/dev/null || fail "normalize_raw_dna self-test"
pass "normalize_raw_dna.py"
python3 scripts/score_pgs.py --self-test >/dev/null || fail "score_pgs self-test"
pass "score_pgs.py"
python3 scripts/clump.py --self-test >/dev/null || fail "clump self-test"
pass "clump.py"
bash -n scripts/prepare_for_imputation.sh || fail "prepare_for_imputation.sh syntax"
pass "prepare_for_imputation.sh (syntax)"
python3 scripts/pii_scan.py --self-test >/dev/null || fail "pii_scan self-test"
pass "pii_scan.py detectors"
python3 scripts/make_report.py --self-test >/dev/null || fail "make_report self-test"
pass "make_report.py"

echo
echo "== end-to-end pipeline on synthetic data =="
# A synthetic 23andMe-format export. These are real rsIDs at real positions but
# the genotype calls are invented -- no human's data is in this repository.
cat > "$TMP/raw.txt" <<'EOF'
# This data file generated by 23andMe at: Wed Jan 01 00:00:00 2020
rsid	chromosome	position	genotype
rs0000001	1	1000	AA
rs0000002	1	2000	CT
rs0000003	1	3000	GC
rs0000004	1	4000	TA
rs0000006	1	6000	--
EOF

python3 scripts/normalize_raw_dna.py "$TMP/raw.txt" -o "$TMP/norm.tsv" >/dev/null \
  || fail "normalize step"
[ -s "$TMP/norm.tsv" ] || fail "normalized output is empty"
lines=$(($(wc -l < "$TMP/norm.tsv") - 1))
[ "$lines" -eq 4 ] || fail "expected 4 normalized variants, got $lines"
pass "normalize: 4 variants, no-call dropped"

cat > "$TMP/score.txt" <<'EOF'
### PGS CATALOG SCORING FILE - synthetic
#pgs_id=PGS999999
rsid	chr_name	chr_position	effect_allele	other_allele	effect_weight
rs0000001	1	1000	A	G	0.10
rs0000002	1	2000	C	T	0.20
rs0000003	1	3000	G	C	0.30
rs0000004	1	4000	T	A	0.40
rs0000005	1	5000	A	G	0.50
EOF

out="$(python3 scripts/score_pgs.py --genome "$TMP/norm.tsv" --score "$TMP/score.txt")" \
  || fail "score step"
grep -q "0.400000" <<<"$out" || fail "expected raw score 0.400000, got: $(grep raw <<<"$out")"
pass "score: raw score 0.400000 as hand-computed"
grep -q "strand-ambiguous (A/T,C/G) : 2" <<<"$out" || fail "palindromic SNPs not skipped"
pass "score: 2 palindromic variants correctly skipped"
grep -qi "not a risk estimate" <<<"$out" || fail "interpretation caveat missing from output"
pass "score: output carries the interpretation caveat"

echo
echo "== zip input handling =="
(cd "$TMP" && zip -q raw.zip raw.txt)
python3 scripts/normalize_raw_dna.py "$TMP/raw.zip" -o "$TMP/norm2.tsv" >/dev/null \
  || fail "zip input"
diff -q "$TMP/norm.tsv" "$TMP/norm2.tsv" >/dev/null \
  || fail "zip and txt inputs produced different output"
pass "zip export parses identically to txt"

echo
echo "== report rendering =="
for style in plain magazine markdown; do
  python3 scripts/make_report.py --demo -o "$TMP/r.$style" --style "$style" >/dev/null \
    || fail "render $style"
  [ -s "$TMP/r.$style" ] || fail "$style output empty"
  grep -qi "not medical advice" "$TMP/r.$style" || fail "$style missing disclaimer"
  pass "$style report renders with disclaimer"
done
grep -q "@media print" "$TMP/r.magazine" || fail "magazine has no print stylesheet"
pass "magazine prints to PDF cleanly"

echo
echo "== repository PII scan =="
python3 scripts/pii_scan.py || fail "PII scan found findings -- see output above"
pass "repository is clean"

echo
printf '\033[32mAll checks passed.\033[0m\n'
